- name: Demo on Command-level Variables
  hosts: all
  vars:
    URL: ping.com
  tasks:
    - name: Printing 1st Varible
      debug:
        msg: "URL = {{URL}}"
    - name: Printing 2nd Varibles
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: pong.com



