- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old Contents Inside Nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download and Extract Frontend Content
  include_role:
    name: common
    tasks_from: download

- name: Copy the Extracted Frontend Content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes
  when: APP_VERSION is not defined

- name: Create App Code Dir
  file:
    path: /usr/share/nginx/html/
    state: directory
  when: APP_VERSION is defined

- name: Download and Extract Content
  ansible.builtin.unarchive:
    src: http://172.31.10.19:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /usr/share/nginx/html/
    remote_src: yes
  when: APP_VERSION is defined

- name: Update Main Nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Update roboshop configuration file
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: COMPONENT is not defined

- name: Update roboshop configuration file for LB
  template:
    src: roboshop-lb.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: COMPONENT is defined


- name: Install Node Exporter
  include_role:
    name: common
    tasks_from: node-exporter

- name: Setup Filebeat
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    LOG_FILE: /var/log/nginx/access.log
    STRUCTURED: "false"
    APP_TYPE: nginx

- name: Restarting Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes