- name: Setup MySQL Repo file
  copy:
    src: /home/centos/Ansible/roles/mysql/file/mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the Default Password
  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
  register: default_mysql_check
  ignore_errors: yes

- name: Grab Default Password
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $(NF-0)}'
  register: out




