- name: Demo on Task-Level Variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Printing 1st Variable
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: yahoo.com
    - name: Printing 2nd Variable
      debug:
        msg: "URL = {{URL}}"

 ## ---> OUTPUT
#TASK [Printing 1st Variable] ***********************************************************************
#ok: [172.31.58.238] => {
#    "msg": "URL = yahoo.com"
#}
#
#TASK [Printing 2nd Variable] ***********************************************************************
#ok: [172.31.58.238] => {
#    "msg": "URL = google.com"
#}

