- name: Demo on Command-level Variables
  hosts: all
  vars:
    URL: ping.com
  tasks:
    - name: Printing 1st Varible
      debug:
        msg: "URL = {{URL}}"
    - name: Printing 2nd Varibles
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: pong.com

## ansible-playbook -i inventory.txt -k -u centos 04-commandlevel_vars.yml -e URL=LOCAL.com

## This will replace everything with URL LOCAL.com



