- name: Demo on Tags
  hosts: localhost
  tasks:
    - name: Ubuntu Task
      debug:
        msg: Ubuntu Task
      tags:
        - name: ubuntu
        - name: debian

    - name: Centos Task
      debug:
        msg: Centos Task
      tags:
        - name: centos
        - name: redhat