- name: Demo on Tags
  hosts: localhost
  tasks:
    - name: Ubuntu Task
      debug:
        msg: Ubuntu Task
      tags:
        - ubuntu
        - debian

    - name: Centos Task
      debug:
        msg: Centos Task
      tags:
        - centOS
        - redhat

- name: Demo on Ubuntu Task Play-Level
  hosts: localhost
  tags:
    - ubuntu
  tasks:
    - name: Ubuntu Task
      debug:
        msg: Ubuntu Ubuntu

- name: Demo on centOS Task Play-Level
  hosts: localhost
  tags:
    - centOS
  tasks:
    - name: centOS Task
      debug:
        msg: centOS centOS