- name: Demo on Tags
  hosts: localhost
  tasks:
    - name: Ubuntu Task
      debug:
        msg: Ubuntu Task
      tags:
        - ubuntu
        - debian

    - name: Centos Task
      debug:
        msg: Centos Task
      tags:
        - centos
        - redhat