- name: Add RoboShop Application User
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Delete Old App Code
  file:
    path: /home/roboshop/{{COMPONENT}}/
    state: absent

- name: Download from github
  include_tasks:
    file: download-from-github.yml
  when: APP_VERSION is not defined


- name: Download from Nexus
  include_tasks:
    file: download-from-nexus.yml
  when: APP_VERSION is defined
