- name: Install NodeJS
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Download App code and Add App User
  include_tasks:
    file: download.yml

- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Acessing Setup-SystemD
  include_tasks:
    file: setup-systemd.yml

- name: Install Node Exporter
  include_tasks:
    file: node-exporter.yml

- name: Nodejs Component Logs
  include_tasks:
    file: filebeat.yml
  vars:
    LOG_FILE: /var/log/{{COMPONENT}}.log
    STRUCTURED: "true"
    APP_TYPE: nodejs
