- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Add RoboShop Application User
  ansible.builtin.user:
    name: roboshop

- name: Bypassing download from Github
  include_tasks:
    file: download.yml

- name: Copy the Extracted catalogue Content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install catalogue Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
    state: latest
  become_user: roboshop

- name: Update SystemD Configuration
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Restart Catalogue Service
  ansible.builtin.systemd:
    name: "catalogue"
    state: restarted
    enabled: yes
    daemon-reload: yes
