- name: Update SystemD Configuration
  copy:
    src: /home/centos/Ansible/roles/{{COMPONENT}}/files/systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes